### ISSUE TITLE
There was a problem saving your preferences. Please try again later

### ISSUE THREAD

**Issue by guoliang** [PotcFdk/SteamDiscoveryQueueAutoSkipper#7]
I get this when I try to start a new queue.

Dunno if this is related with the script, but I don't get that error dialog when the script is turned off at least

Check [here](https://imgur.com/U6RnzA6) for the dialog

**Comment by guoliang** [comment]
[https://imgur.com/U6RnzA6](url)

**Comment by RedSparr0w** [comment]
Haven't had this appear on my profile,
Do you have any other steam extensions installed?

--------------------
Image from above:
![](https://i.imgur.com/U6RnzA6.png)

**Comment by callmenemo491** [comment]
it appears to be a harmless popup.  i dont do anything and the script does it magic, and continues

**Comment by PotcFdk** [comment]
Seems to be covered by #6 part 1 already.
