### ISSUE TITLE
Script got stuck once after clicking the automatic popup

### ISSUE THREAD

**Issue by VADemon** [PotcFdk/SteamDiscoveryQueueAutoSkipper#9]
Version: latest, 0.8.0
Browser: Firefox 85b4

What happened:

1. Loaded homepage tab
2. Clicked scripts popup (awesome btw, thanks)
3. Check back later, its stuck on what's seemingly the first store page, with a <blue> queue button. It's HTML code was:

```
<a href="https://store.steampowered.com/explore/?snr=1_5_9_" class="btnv6_blue_hoverfade  btn_medium  right" data-tooltip-text="View and customize your personal Discovery Queue.">
									<span>View Your Queue&nbsp;&nbsp;&nbsp;<i class="ico16 arrow_next"></i></span>
								</a>
```

Then I went to the queue page manually (the overview page), got a popup "there's an error saving preferences" and it auto-started from there.

Not sure what went wrong, 3 other accs launched fine at the exact same time.

❤

EDIT/PS: I have the .html source for the store page for that account open in a tab (before I restarted the queue), if needed for debugging.

**Comment by PotcFdk** [comment]
It looks like I can't reach the Steam servers at all right now. I assume this to be a serverside issue. Especially the "there's an error saving preferences" is not related to this script at all.
What probably happened is that it sent the request but the steam servers just refused to cooperate. When I can visit the Steam store again I will see if I can figure out what might have caused the behavior that you described.

**Comment by VADemon** [comment]
There're still more days to come and it was the first occurrence of, I think, 9. I will update if I encounter it again, because your explanation is plausible, it was also shortly after the daily reset. 

Let's leave it at that?.. although, upon reloading the home page, no prompt had appeared (the script was probably thinking its in the queue?)

Oh. I forgot to upload the page I witnessed. Even if I included the html markup:
![80](https://user-images.githubusercontent.com/1168140/103242765-c3bf2b00-4957-11eb-9e17-0bdf0e50d5fe.jpg)

**Comment by PotcFdk** [comment]
> although, upon reloading the home page, no prompt had appeared (the script was probably thinking its in the queue?)
It could be that the current code is not handling the case well when a queue was started but not finished. I'll test this later.

**Comment by PotcFdk** [comment]
I just tried around a little bit and it seems like when a queue is already started, the `https://store.steampowered.com/explore/` page still behaves as if it wasn't. That means, the script will detect the unfinished queue and still offer to begin (or actually resume) it. The issue that you probably saw is that as soon as the notification is shown, a flag is set that prevents the notification from being shown for the next hour. So it seems like the "worst case" here is the fact that if the steam servers error out during that particular request (or set of requests), the notification will not show up for another hour. IMO that's acceptable behavior, seeing as
a) the notification should re-appear after an hour
b) if the user notices that something's off (i.e. they didn't get any card) and will probably attempt to manually start the queue, which will get the script going again
Even if b is not the perfect solution, the notification would have still done its job of *reminding* that there are cards to get.

If you're okay with that, I'd close this issue for now. I might implement better interruption detection (and handling) at some point in the future which would allow us to reset/remove that flag if a full queue processing interruption is detected, but in either case this feels like an excessive amount of work for the little benefit at hand (for now).

**Comment by VADemon** [comment]
Thank you for the explanation. I just came back to report this again happened as I launched my 4 accs one after another, this time on a different one, exactly the same symptoms. I will wait that 1 hour and see if I can continue with the new popup.
